const products = [
  {
    name: "Premium Alphonso Mango",
    slug: "premium-alphonso-mango",
    description: "Naturally ripened sweet mangoes from Aaranya.",
    image: "https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&w=1200&q=80",
    price: 220,
    unit: "kg",
    category: "fruits",
    tags: ["fruits", "organic"],
    isFeaturedMango: true,
    isOrganic: false,
    isInSeason: false,
    stock: 150,
  },
  {
    name: "Farm Fresh Tomato",
    slug: "farm-fresh-tomato",
    description: "Bright red, juicy tomatoes picked daily.",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg",
    price: 45,
    unit: "kg",
    category: "vegetables",
    tags: ["vegetables", "organic"],
    isOrganic: false,
    isInSeason: false,
    stock: 300,
  },
  {
    name: "Whole Wheat Flour",
    slug: "whole-wheat-flour",
    description: "Stone-ground wheat flour for soft rotis.",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=1200&q=80",
    price: 55,
    unit: "kg",
    category: "grains",
    tags: ["grains", "organic"],
    isOrganic: false,
    isInSeason: false,
    stock: 200,
  },
  {
    name: "Rice Flour",
    slug: "rice-flour",
    description: "Freshly milled fine rice flour.",
    image: "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1200&q=80",
    price: 68,
    unit: "kg",
    category: "grains",
    tags: ["grains", "non-organic"],
    isOrganic: false,
    isInSeason: false,
    stock: 140,
  },
  {
    name: "Desi Jaggery (Gur)",
    slug: "desi-jaggery-gur",
    description: "Traditional chemical-free jaggery blocks.",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80",
    price: 95,
    unit: "kg",
    category: "organic",
    tags: ["organic"],
    isOrganic: false,
    isInSeason: false,
    stock: 120,
  },
  {
    name: "Natural Shakkar",
    slug: "natural-shakkar",
    description: "Unrefined farm-made shakkar with rich taste.",
    image: "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?auto=format&fit=crop&w=1200&q=80",
    price: 85,
    unit: "kg",
    category: "organic",
    tags: ["organic"],
    isOrganic: false,
    isInSeason: false,
    stock: 100,
  },
  {
    name: "Fresh Sugarcane",
    slug: "fresh-sugarcane",
    description: "Freshly harvested juicy sugarcane stalks.",
    image: "https://images.unsplash.com/photo-1590086782792-42dd2350140d?auto=format&fit=crop&w=1200&q=80",
    price: 35,
    unit: "piece",
    category: "non-organic",
    tags: ["non-organic"],
    isOrganic: false,
    isInSeason: false,
    stock: 250,
  },
  {
    name: "Daily Fresh Vegetable Box - Small",
    slug: "daily-fresh-vegetable-box-small",
    description: "Mixed vegetables bundle for a small family.",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
    price: 199,
    unit: "box",
    category: "vegetables",
    tags: ["vegetables", "organic", "daily-box"],
    isOrganic: false,
    isInSeason: false,
    stock: 80,
  },
  {
    name: "Daily Fresh Vegetable Box - Medium",
    slug: "daily-fresh-vegetable-box-medium",
    description: "Mixed vegetables bundle for medium-sized households.",
    image: "https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=1200&q=80",
    price: 299,
    unit: "box",
    category: "vegetables",
    tags: ["vegetables", "organic", "daily-box"],
    isOrganic: false,
    isInSeason: false,
    stock: 65,
  },
  {
    name: "Daily Fresh Vegetable Box - Large",
    slug: "daily-fresh-vegetable-box-large",
    description: "Mixed vegetables bundle for larger families.",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=1200&q=80",
    price: 499,
    unit: "box",
    category: "vegetables",
    tags: ["vegetables", "organic", "daily-box"],
    isOrganic: false,
    isInSeason: false,
    stock: 40,
  },
];

export default products;
